# Generated by Django 5.1 on 2024-09-20 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNivel', models.CharField(blank=True, max_length=48, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrado', models.CharField(blank=True, max_length=48, null=True)),
                ('nivelRelacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoApp.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrado', models.CharField(blank=True, max_length=48, null=True)),
                ('gradoRelacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoApp.grado')),
                ('nivelRelacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecoApp.nivel')),
            ],
        ),
    ]
